public class Finals {
    public static void main(String[] args) {
        if (true) {
            System.out.println("Finals");

            Scanner scanner = new Scanner(System.in);
            System.out.println("Enter PassWord:");
            String password = scanner.nextLine();
            System.out.println("Wrong Password!");
            String password2 = scanner.nextLine();
            System.out.println("Enter Password:");
            String password3 = scanner.nextLine();
            System.out.println("Wrong Password!");
            String password4 = scanner.nextLine();
            System.out.println("Enter Password:");
            String password5 = scanner.nextLine();
            System.out.println("Access Granted!");
        }